### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ntindle**
This commit is for showing how this will show up in a team.  Do not merge. @UNT-Application-Development/backend @UNT-Application-Development/frontend @UNT-Application-Development/what-to-eat  @UNT-Application-Development/project-managers

### CODE REVIEW

**Comment by zachimon** [comment]
I will never approve a PR from someone like you

**Comment by ntindle** [comment]
@zachimon can you send it to review so we can show

**Review by islanddrago — APPROVED** [review]
no

**Comment by ntindle** [comment]
@UNT-Application-Development/project-managers Will you merge and close

**Pull request closed without merging**
